package lecture_8;

import java.util.Objects;

class Person {
    private String name;
    private int age;

    public Person(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    // generated by IDE (Alt+Insert)

    @Override
    public boolean equals(Object o) {

        // self check
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        // type check and cast
        Person person = (Person) o;

        // field comparison
        return age == person.age && Objects.equals(name, person.name);
    }

    @Override
    public int hashCode() {
        // field hashes
        return Objects.hash(name, age);
    }


    @Override
    public String toString() {
        // for debugging purposes print all fields of object
        return "Person{" +
               "name='" + name + '\'' +
               ", age=" + age +
               '}';
    }
}